site_name: Knowledgebase
site_author: Maik Käseberg
theme:
  name: material
  font: false
  favicon: icon/icon.ico
  logo: icon/icon.png
  icon:
    admonition:
      info: material/alarm
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: '#00305d'
    accent: '#255f8b'
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: '#00305d'
    accent: '#255f8b'
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  features:
  - navigation.top
  - navigation.tabs
  - navigation.instant
  - navigation.sections
  - toc.integrate
  - content.tabs
  - content.code.copy
  - content.code.annotate
  - content.action.edit
  - content.action.view
  - search.suggest
  - search.highlight
  - search.share
  - navigation.footer
  - navigation.indexes
  - navigation.tracking
  - navigation.path
  - content.tooltips
  - palette
plugins:
- search
- gen-files:
    scripts:
    - docs/gen_nav.py
- literate-nav:
    nav_file: SUMMARY.txt
extra_css:
- css/extra.css
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/road2Goat31/obsidian-wiki
  generator: false
nav: []
