site_author: Maik Käseberg
site_name: Knowledgebase
theme:
    favicon: icon/icon.ico
    features:
    - navigation.top
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - toc.integrate
    - content.tabs
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.path
    - content.tooltips
    - palette
    font: false
    icon:
        admonition:
            info: material/alarm
    logo: icon/icon.png
    name: material
    custom_dir: docs/overrides
    palette:
    -   accent: '#255f8b'
        media: '(prefers-color-scheme: light)'
        primary: '#00305d'
        scheme: default
        toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
    -   accent: '#255f8b'
        media: '(prefers-color-scheme: dark)'
        primary: '#00305d'
        scheme: slate
        toggle:
            icon: material/toggle-switch
            name: Switch to light mode
    -   accent: '#255f8b'
        media: '(prefers-color-scheme: light)'
        primary: '#00305d'
        scheme: default
        toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
    -   accent: '#255f8b'
        media: '(prefers-color-scheme: dark)'
        primary: '#00305d'
        scheme: slate
        toggle:
            icon: material/toggle-switch
            name: Switch to light mode
analytics:
  gtag: null
shortcuts:
  help: 191    # ?
  next: 78     # n
  previous: 80 # p
  search: 83   # s
extra:
    generator: false
    social:
    -   icon: fontawesome/brands/github
        link: https://github.com/road2Goat31/obsidian-wiki
extra_css:
- css/extra.css
extra_javascript:
- js/print-button.js
plugins:
- search
nav:
-   Home: index.md
-   Technologien:
    -   Ansible:
        -   praktische_Uebungen:
            -   Aufgabe_Switch: Knowledgebase/1_Technologien/Ansible/praktische_Uebungen/Aufgabe_Switch.md
            -   Beispiel_Testumgebung: Knowledgebase/1_Technologien/Ansible/praktische_Uebungen/Beispiel_Testumgebung.md
        -   Wissen:
            -   01_Grundlagen:
                -   1_Erläuterung zu Ansible: Knowledgebase/1_Technologien/Ansible/Wissen/01_Grundlagen/1_Erläuterung
                        zu Ansible.md
                -   2_Begriffe und Konzepte: Knowledgebase/1_Technologien/Ansible/Wissen/01_Grundlagen/2_Begriffe
                        und Konzepte.md
                -   3_Funktionsweise Ansible: Knowledgebase/1_Technologien/Ansible/Wissen/01_Grundlagen/3_Funktionsweise
                        Ansible.md
                -   4_Beispiele und Tutorials: Knowledgebase/1_Technologien/Ansible/Wissen/01_Grundlagen/4_Beispiele
                        und Tutorials.md
            -   02_Starten mit Ansible:
                -   Installation von Ansible: Knowledgebase/1_Technologien/Ansible/Wissen/02_Starten
                        mit Ansible/Installation von Ansible.md
            -   03_Best Practices:
                -   ansible-dir: Knowledgebase/1_Technologien/Ansible/Wissen/03_Best
                        Practices/ansible-dir.md
                -   ansible-doku: Knowledgebase/1_Technologien/Ansible/Wissen/03_Best
                        Practices/ansible-doku.md
                -   ansible-inventory: Knowledgebase/1_Technologien/Ansible/Wissen/03_Best
                        Practices/ansible-inventory.md
                -   ansible-playbook: Knowledgebase/1_Technologien/Ansible/Wissen/03_Best
                        Practices/ansible-playbook.md
            -   04_cli-tools:
                -   Ansible-Builder: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Builder.md
                -   Ansible-Config: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Config.md
                -   Ansible-Doc: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Doc.md
                -   Ansible-Galaxy: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Galaxy.md
                -   Ansible-Inventory: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Inventory.md
                -   Ansible-Lint: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Lint.md
                -   Ansible-Navigator: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Navigator.md
                -   Ansible-Playbook: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Playbook.md
                -   Ansible-Vault: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Vault.md
                -   Wichtige Befehle: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Wichtige
                        Befehle.md
            -   05_Komponenten:
                -   ansible playbooks: Knowledgebase/1_Technologien/Ansible/Wissen/05_Komponenten/ansible
                        playbooks.md
                -   ansible roles: Knowledgebase/1_Technologien/Ansible/Wissen/05_Komponenten/ansible
                        roles.md
                -   Collections:
                    -   Installation und Verwendung: Knowledgebase/1_Technologien/Ansible/Wissen/05_Komponenten/Collections/Installation
                            und Verwendung.md
                -   Module:
                    -   ansible-win-desired-state-configuration: Knowledgebase/1_Technologien/Ansible/Wissen/05_Komponenten/Module/ansible-win-desired-state-configuration.md
                    -   ansible.builtin:
                        -   command: Knowledgebase/1_Technologien/Ansible/Wissen/05_Komponenten/Module/ansible.builtin/command.md
                        -   copy: Knowledgebase/1_Technologien/Ansible/Wissen/05_Komponenten/Module/ansible.builtin/copy.md
                        -   debug: Knowledgebase/1_Technologien/Ansible/Wissen/05_Komponenten/Module/ansible.builtin/debug.md
                        -   quote: Knowledgebase/1_Technologien/Ansible/Wissen/05_Komponenten/Module/ansible.builtin/quote.md
                        -   shell: Knowledgebase/1_Technologien/Ansible/Wissen/05_Komponenten/Module/ansible.builtin/shell.md
            -   06_GUI:
                -   Ansible Forms: Knowledgebase/1_Technologien/Ansible/Wissen/06_GUI/Ansible
                        Forms.md
                -   Semaphore:
                    -   Semaphore mit Docker unter Ubuntu: Knowledgebase/1_Technologien/Ansible/Wissen/06_GUI/Semaphore/Semaphore
                            mit Docker unter Ubuntu.md
                    -   Semaphore mit apt: Knowledgebase/1_Technologien/Ansible/Wissen/06_GUI/Semaphore/Semaphore
                            mit apt.md
            -   07_ Sonstiges:
                -   Dev-Tools: Knowledgebase/1_Technologien/Ansible/Wissen/07_ Sonstiges/Dev-Tools.md
                -   Priviledged User Linux: Knowledgebase/1_Technologien/Ansible/Wissen/07_
                        Sonstiges/Priviledged User Linux.md
                -   ansible-become-priviledge-escalation: Knowledgebase/1_Technologien/Ansible/Wissen/07_
                        Sonstiges/ansible-become-priviledge-escalation.md
                -   jinja-templating: Knowledgebase/1_Technologien/Ansible/Wissen/07_
                        Sonstiges/jinja-templating.md
                -   potentielle-probleme: Knowledgebase/1_Technologien/Ansible/Wissen/07_
                        Sonstiges/potentielle-probleme.md
    -   Cisco:
        -   Grundlegend: Knowledgebase/1_Technologien/Cisco/Grundlegend.md
        -   Router:
            -   1_Basiskonfigurationen: Knowledgebase/1_Technologien/Cisco/Router/1_Basiskonfigurationen.md
            -   2_Zugriff absichern: Knowledgebase/1_Technologien/Cisco/Router/2_Zugriff
                    absichern.md
            -   3_SSH: Knowledgebase/1_Technologien/Cisco/Router/3_SSH.md
            -   4_Interface konfigurieren: Knowledgebase/1_Technologien/Cisco/Router/4_Interface
                    konfigurieren.md
            -   5_DHCP: Knowledgebase/1_Technologien/Cisco/Router/5_DHCP.md
            -   Grundlegend: Knowledgebase/1_Technologien/Cisco/Router/Grundlegend.md
            -   Troubleshooting: Knowledgebase/1_Technologien/Cisco/Router/Troubleshooting.md
        -   Switch:
            -   1_Inital Settings: Knowledgebase/1_Technologien/Cisco/Switch/1_Inital
                    Settings.md
            -   2_Gesicherter Zugriff (SSH): Knowledgebase/1_Technologien/Cisco/Switch/2_Gesicherter
                    Zugriff (SSH).md
            -   3_VLAN: Knowledgebase/1_Technologien/Cisco/Switch/3_VLAN.md
            -   4_PortChannel (LAG): Knowledgebase/1_Technologien/Cisco/Switch/4_PortChannel
                    (LAG).md
            -   5_(R)STP: Knowledgebase/1_Technologien/Cisco/Switch/5_(R)STP.md
            -   6_Security: Knowledgebase/1_Technologien/Cisco/Switch/6_Security.md
    -   Grundlegend:
        -   IPv6: Knowledgebase/1_Technologien/Grundlegend/IPv6.md
-   Aufgaben:
    -   1_Semester:
        -   '24_10': Knowledgebase/2_Aufgaben/1_Semester/24_10.md
        -   '24_11': Knowledgebase/2_Aufgaben/1_Semester/24_11.md
        -   '24_12': Knowledgebase/2_Aufgaben/1_Semester/24_12.md
        -   '25_01': Knowledgebase/2_Aufgaben/1_Semester/25_01.md
        -   '25_02': Knowledgebase/2_Aufgaben/1_Semester/25_02.md
-   Belegarbeit:
    -   Notizen_Belegarbeit: Knowledgebase/5_Belegarbeit/Notizen_Belegarbeit.md
