site_name: Knowledgebase

site_author: "Maik Käseberg"

theme:
  name: material
  font: false
  favicon: icon/icon.ico
  logo: icon/icon.png
  icon:
    admonition:
      info: material/alarm 
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "#00305d"
      accent: "#255f8b"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "#00305d"
      accent: "#255f8b"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - toc.integrate
    - content.tabs
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.path
    - content.tooltips
    - palette

  
extra_css:
  - css/extra.css
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/road2Goat31/obsidian-wiki
  generator: false  # Entfernt "Made with MkDocs"


nav:
  - Home: index.md
  - Technologien:
      - Ansible:
          - Grundlagen:
              - Erläuterung zu Ansible: Knowledgebase/1_Technologien/Ansible/Wissen/01_Grundlagen/1_Erläuterung zu Ansible.md
              - Begriffe und Konzepte: Knowledgebase/1_Technologien/Ansible/Wissen/01_Grundlagen/2_Begriffe und Konzepte.md
              - Funktionsweise Ansible: Knowledgebase/1_Technologien/Ansible/Wissen/01_Grundlagen/3_Funktionsweise Ansible.md
              - Beispiele und Tutorials: Knowledgebase/1_Technologien/Ansible/Wissen/01_Grundlagen/4_Beispiele und Tutorials.md
          - Starten mit Ansible:
              - Installation von Ansible: Knowledgebase/1_Technologien/Ansible/Wissen/02_Starten mit Ansible/Installation von Ansible.md
          - Best Practices:
              - Ansible Verzeichnisstruktur: Knowledgebase/1_Technologien/Ansible/Wissen/03_Best Practices/ansible-dir.md
              - Dokumentation: Knowledgebase/1_Technologien/Ansible/Wissen/03_Best Practices/ansible-doku.md
              - Inventory: Knowledgebase/1_Technologien/Ansible/Wissen/03_Best Practices/ansible-inventory.md
              - Playbook: Knowledgebase/1_Technologien/Ansible/Wissen/03_Best Practices/ansible-playbook.md
          - CLI-Tools:
              - Ansible-Builder: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Builder.md
              - Ansible-Config: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Config.md
              - Ansible-Doc: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Doc.md
              - Ansible-Galaxy: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Galaxy.md
              - Ansible-Inventory: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Inventory.md
              - Ansible-Lint: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Lint.md
              - Ansible-Navigator: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Navigator.md
              - Ansible-Playbook: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Playbook.md
              - Ansible-Vault: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Ansible-Vault.md
              - Wichtige Befehle: Knowledgebase/1_Technologien/Ansible/Wissen/04_cli-tools/Wichtige Befehle.md
          - Komponenten:
              - Playbooks: Knowledgebase/1_Technologien/Ansible/Wissen/05_Komponenten/ansible playbooks.md
              - Rollen: Knowledgebase/1_Technologien/Ansible/Wissen/05_Komponenten/ansible roles.md
              - Collections:
                  - Installation und Verwendung: Knowledgebase/1_Technologien/Ansible/Wissen/05_Komponenten/Collections/Installation und Verwendung.md
              - Module:
                  - ansible.builtin:
                      - command: Knowledgebase/1_Technologien/Ansible/Wissen/05_Komponenten/Module/ansible.builtin/command.md
                      - copy: Knowledgebase/1_Technologien/Ansible/Wissen/05_Komponenten/Module/ansible.builtin/copy.md
                      - debug: Knowledgebase/1_Technologien/Ansible/Wissen/05_Komponenten/Module/ansible.builtin/debug.md
                      - quote: Knowledgebase/1_Technologien/Ansible/Wissen/05_Komponenten/Module/ansible.builtin/quote.md
                      - shell: Knowledgebase/1_Technologien/Ansible/Wissen/05_Komponenten/Module/ansible.builtin/shell.md
          - GUI:
              - Ansible Forms: Knowledgebase/1_Technologien/Ansible/Wissen/06_GUI/Ansible Forms.md
              - Semaphore:
                  - Installation mit apt: Knowledgebase/1_Technologien/Ansible/Wissen/06_GUI/Semaphore/Semaphore mit apt.md
                  - Installation mit Docker: Knowledgebase/1_Technologien/Ansible/Wissen/06_GUI/Semaphore/Semaphore mit Docker unter Ubuntu.md
          - Sonstiges:
              - Privileged Escalation: Knowledgebase/1_Technologien/Ansible/Wissen/07_ Sonstiges/ansible-become-priviledge-escalation.md
              - Dev-Tools: Knowledgebase/1_Technologien/Ansible/Wissen/07_ Sonstiges/Dev-Tools.md
              - Jinja-Templating: Knowledgebase/1_Technologien/Ansible/Wissen/07_ Sonstiges/jinja-templating.md
              - Potenzielle Probleme: Knowledgebase/1_Technologien/Ansible/Wissen/07_ Sonstiges/potentielle-probleme.md
              - Privileged User Linux: Knowledgebase/1_Technologien/Ansible/Wissen/07_ Sonstiges/Priviledged User Linux.md
      - Cisco:
          - Grundlegend: Knowledgebase/1_Technologien/Cisco/Grundlegend.md
          - Router:
              - Basiskonfigurationen: Knowledgebase/1_Technologien/Cisco/Router/1_Basiskonfigurationen.md
              - Zugriff absichern: Knowledgebase/1_Technologien/Cisco/Router/2_Zugriff absichern.md
              - SSH: Knowledgebase/1_Technologien/Cisco/Router/3_SSH.md
              - Interface konfigurieren: Knowledgebase/1_Technologien/Cisco/Router/4_Interface konfigurieren.md
              - DHCP: Knowledgebase/1_Technologien/Cisco/Router/5_DHCP.md
              - Troubleshooting: Knowledgebase/1_Technologien/Cisco/Router/Troubleshooting.md
          - Switch:
              - Initial Settings: Knowledgebase/1_Technologien/Cisco/Switch/1_Inital Settings.md
              - Gesicherter Zugriff (SSH): Knowledgebase/1_Technologien/Cisco/Switch/2_Gesicherter Zugriff (SSH).md
              - VLAN: Knowledgebase/1_Technologien/Cisco/Switch/3_VLAN.md
              - PortChannel (LAG): Knowledgebase/1_Technologien/Cisco/Switch/4_PortChannel (LAG).md
              - (R)STP: Knowledgebase/1_Technologien/Cisco/Switch/5_(R)STP.md
              - Security: Knowledgebase/1_Technologien/Cisco/Switch/6_Security.md
      - Grundlagen:
          - IPv6: Knowledgebase/1_Technologien/Grundlegend/IPv6.md
  - Aufgaben:
      - 1. Semester:
          - Oktober 2024: Knowledgebase/2_Aufgaben/1_Semester/24_10.md
          - November 2024: Knowledgebase/2_Aufgaben/1_Semester/24_11.md
          - Dezember 2024: Knowledgebase/2_Aufgaben/1_Semester/24_12.md
          - Januar 2025: Knowledgebase/2_Aufgaben/1_Semester/25_01.md
          - Februar 2025: Knowledgebase/2_Aufgaben/1_Semester/25_02.md
      - 2. Semester: Knowledgebase/2_Aufgaben/2_Semester/
  #- Vorlagen: Knowledgebase/3_Vorlagen/
  #- Testbereich:
      #- Testdatei: Knowledgebase/4_Test/Test.md
  - Belegarbeit:
      - Notizen: Knowledgebase/5_Belegarbeit/Notizen_Belegarbeit.md
      - Vorlage Bachelorarbeit: Knowledgebase/5_Belegarbeit/Vorlage_Bachelorarbeit_Wirtschaftsinformatik_DD.docx

