name: Deploy MkDocs

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v4

      - name: Python & Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material pyyaml mkdocs-gen-files mkdocs-literate-nav

      - name: Automatisch mkdocs.yml aktualisieren
        run: python gen_nav.py

      - name: Änderungen committen (falls nötig)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automatische Aktualisierung der Webseite" && git push)

      - name: Webseite bauen & deployen
        run: mkdocs gh-deploy --force
